time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
time ./scrabble-suggester "et" 10 
